### ISSUE TITLE
results table display

### ISSUE THREAD

**Issue by ghost** [emredurak01/AssignIt#1]
When the run button is clicked, the results table displays only the first line of the process output. However, the expected behaviour is displaying all the lines. The comparison works as intended and the output is printed out correctly. If there is no obvious solution, a new way to display output may be required. Showing only the passed status of the submission is also a solution. Since it affects only the GUI, it is a low priority issue.

**Comment by HumayOzer** [comment]
i fixed that issue with handleRowSelection() method. when we select and click the details button we can see all
